version: "3"

services:
  nozerodays:
    build:
      context: ../
      dockerfile: ./Dockerfile
    command: ["--username=$GITHUB_USERNAME", "--accessToken=$GITHUB_ACCESS_TOKEN", "--organizations=$ORGANIZATIONS", "--webhook=$WEBHOOK_URL", "--location=$LOCATION"]
