apiVersion: apps/v1
kind: Deployment
metadata:
  name: nozerodays-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nozerodays-bot
  template:
    metadata:
      labels:
        app: nozerodays-bot
    spec:
      containers:
      - name: nginx
        image: digitalocean/doks-example
        env:
        - name: LOCATION
          value: "America/Los_Angeles"
        - name: ORGANIZATIONS
          value: "goodbuns"
        - name: WEBHOOK_URL
          valueFrom:
          secretKeyRef:
            name: nozerodays
            key: webhook-url
        - name: GITHUB_ACCESS_TOKEN
          valueFrom:
          secretKeyRef:
            name: nozerodays
            key: github-access-token
        - name: GITHUB_USERNAME
          valueFrom:
          secretKeyRef:
            name: nozerodays
            key: username
