name: cd

on:
  push:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code
        uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.GITHUB_ACCESS_TOKEN }} docker.pkg.github.com
      - name: Build docker image 
        run: docker build -t docker.pkg.github.com/goodbuns/nozerodays/nozerodays:$GITHUB_SHA -t docker.pkg.github.com/goodbuns/nozerodays/nozerodays:latest .
      - name: Push docker image
        run: docker push docker.pkg.github.com/goodbuns/nozerodays/nozerodays:$GITHUB_SHA
      - name: Push latest tag for docker image
        run: docker push docker.pkg.github.com/goodbuns/nozerodays/nozerodays:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up kubectl
      uses: matootie/dokube@v1.2.0
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: production
        expirationTime: 300
    - name: Check out code
      uses: actions/checkout@v1
    - name: Deploy
      run: kubectl apply -f deployments/nozerodays.yaml
